language: java
dist: trusty
jdk:
  - oraclejdk8
install:
  - travis_wait 30 mvn install -q
script:
  - mvn verify -P IT -B -q -pl bahmni-emr-api/
  - mvn verify -P IT -B -q -pl bahmnicore-api/
  - mvn verify -P IT -B -q -pl bahmnicore-omod/